" CocExtensions
let g:coc_global_extensions = [
\ 'coc-conjure-olical',
\ 'coc-css',
\ 'coc-emmet',
\ 'coc-eslint',
\ 'coc-go',
\ 'coc-html',
\ 'coc-json',
\ 'coc-lua',
\ 'coc-marketplace',
\ 'coc-prettier',
\ 'coc-project',
\ 'coc-python',
\ 'coc-rls',
\ 'coc-rust-analyzer',
\ 'coc-snippets',
\ 'coc-tailwindcss',
\ 'coc-tsserver',
\ 'coc-ultisnips',
\ 'coc-yaml'
\ ]
